/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddClassroom`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClassroomPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/JoinClassScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ScanQR`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/firebase/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AddClassroom`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ClassroomPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/JoinClassScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ScanQR`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/firebase/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/screens/AddClassroom${`?${string}` | `#${string}` | ''}` | `/screens/ClassroomPage${`?${string}` | `#${string}` | ''}` | `/screens/Home${`?${string}` | `#${string}` | ''}` | `/screens/JoinClassScreen${`?${string}` | `#${string}` | ''}` | `/screens/Login${`?${string}` | `#${string}` | ''}` | `/screens/Register${`?${string}` | `#${string}` | ''}` | `/screens/ScanQR${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddClassroom`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClassroomPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/JoinClassScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ScanQR`; params?: Router.UnknownInputParams; };
    }
  }
}
